### ISSUE TITLE
Definition of Envs required default value

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/cli#68]
The env variables defined in the mesg.yml required to have a default value (even empty) for the service to be valid:

Not valid:
```yml
configuration:
  env:
    - SENDGRID_API_KEY
```

Valid:
```yml
configuration:
  env:
    - SENDGRID_API_KEY=
```

Is it really what we expect?
